import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-new-gr-c-s-check-loaded data-gr-ext-installed lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
